crew_name: Donor_Intelligence_Crew
process: sequential
description: >
  A multi-agent CrewAI system for donor profiling, landscape analysis, and fundraising strategy generation.

agents:
  - name: DonorResearchAgent
    role: Web & Document Scraper
    goal: Extract donor insights from online sources and donor websites
    backstory: >
      An expert research analyst trained in navigating donor websites and official documents to collect real-time intelligence.
    prompt_path: prompts/donor_research_prompt.txt

  - name: ProfileSynthesizerAgent
    role: Profile Compiler
    goal: Merge structured research data and past donor info into a coherent donor profile
    backstory: >
      An expert research analyst trained in navigating donor websites and official documents to collect real-time intelligence.
    prompt_path: prompts/profile_synthesizer_prompt.txt

  - name: ReportWriterAgent
    role: Donor Report Generator
    goal: Create custom reports from profiles, tailored by user needs
    backstory: >
      An expert research analyst trained in navigating donor websites and official documents to collect real-time intelligence.
    prompt_path: prompts/report_writer_prompt.txt

  - name: GuidanceAgent
    role: Engagement Instructions Advisor
    goal: Suggest donor-specific outreach instructions and standard engagement practices
    backstory: >
      An expert research analyst trained in navigating donor websites and official documents to collect real-time intelligence.
    prompt_path: prompts/guidance_prompt.txt

  - name: StrategyRecommenderAgent
    role: Fundraising Strategist
    goal: Propose strategic engagement angles based on donor priorities
    backstory: >
      An expert research analyst trained in navigating donor websites and official documents to collect real-time intelligence.
    prompt_path: prompts/strategy_recommender_prompt.txt

  - name: GovernanceAgent
    role: Role-Based Redactor
    goal: Filter or redact content based on user’s access level
    backstory: >
      An expert research analyst trained in navigating donor websites and official documents to collect real-time intelligence.
    prompt_path: prompts/governance_prompt.txt

# Task routing is now handled in main.py
