ResearchDonorProfile_Task:
  description: Collect online insights about the donor
  agent: Donor_Research_Agent
  expected_output: >
    A ResearchData object containing a list of all found insights.

SynthesizeDonorProfile_Task:
  description: Build a profile from research and previous donor records
  agent: Profile_Synthesizer_Agent
  expected_output: >
    A DonorProfile object containing the full, structured profile of the donor.

RecommendStrategy_Task:
  description: Suggest engagement strategy based on donor profile
  agent: Strategy_Recommender_Agent
  expected_output: >
    A string containing a strategic recommendation and its justification.

AddEngagementTips_Task:
  description: Provide standard outreach instructions based on donor type
  agent: Guidance_Agent
  expected_output: >
    A string containing engagement instructions, funding cycle info, and advisory notes.

GenerateReport_Task:
  description: Produce a fundraising report tailored to audience
  agent: Report_Writer_Agent
  expected_output: >
    A string containing the full, editable donor intelligence report.

ApplyGovernance_Task:
  description: Redact sensitive information based on user role
  agent: Governance_Agent
  expected_output: >
    A final string containing the finalized donor report with sensitive content redacted.