from docx import Document
from docx.shared import Pt
from docx.enum.style import WD_STYLE_TYPE

def generate_docx(text: str, output_path: str):
    """
    Generate a formatted .docx Word document from plain text.
    
    :param text: Full report text (as generated by CrewAI).
    :param output_path: Path to save the output Word document.
    """
    doc = Document()

    # Define styles
    styles = doc.styles
    if "DonorHeading" not in styles:
        heading_style = styles.add_style("DonorHeading", WD_STYLE_TYPE.PARAGRAPH)
        heading_font = heading_style.font
        heading_font.name = 'Arial'
        heading_font.size = Pt(14)
        heading_font.bold = True

    if "DonorBody" not in styles:
        body_style = styles.add_style("DonorBody", WD_STYLE_TYPE.PARAGRAPH)
        body_font = body_style.font
        body_font.name = 'Calibri'
        body_font.size = Pt(11)

    # Split text into lines to detect headers and sections
    lines = text.strip().split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.endswith(":") or line.lower().startswith("section"):
            doc.add_paragraph(line, style="DonorHeading")
        else:
            doc.add_paragraph(line, style="DonorBody")

    # Save the document
    doc.save(output_path)
